### PR TITLE
import_action: Added check for dataset.headers (#1192)

### PR DESCRIPTION
**Pull request by matthewhegarty**
**Problem**

If one tries to import a file with an empty first row via the Admin site, then there is a confusing exception reported.

**Solution**

How did you solve the problem?

- Add a check for `dataset.headers` in admin `import_action()`, and add a form error if there is no header row.
- Added a check in `import.html` for the presence of the 'fields' property - this will not be populated if there is an error.
- Errors raised during import are now presented as form errors instead of returned in the HTTP response.
  - This could affect the way that clients handle these errors, so have marked the PR as 'breaking change'. 
 - Test class `ImportActionDecodeErrorTest` is removed (superseded by new form error tests)

**Acceptance Criteria**

- Added unit tests
- Ran test suite

### CODE REVIEW

**Review by manelclos — APPROVED** [review]
LGTM, improves the UX

**Comment by manelclos** [comment]
@matthewhegarty thanks! While reviewing the code I checked that we *really* depend on the headers, and we do, here:
https://github.com/django-import-export/django-import-export/blob/722c376e476f0a9b5252c21d4cf788c9bdd1bdd8/import_export/resources.py#L785

To improve this PR, what about checking for `dataset.headers` just before trying to access `dataset.dict`? We could throw a meaningful exception that will help in the general case.

For the admin, checking and generating a field error as you did is really awesome for the UX.

Please let me know what you think.

**Comment by matthewhegarty** [comment]
@manelclos Thanks for reviewing.  I'll look into this further.  I'm going to move this to draft because this changes similar code to #1277.  

Also there are further opportunities for UX improvements, in terms of handling the decode() exceptions.  At this moment, this returns a [HTTP 200 with an error message](https://github.com/django-import-export/django-import-export/blob/722c376e476f0a9b5252c21d4cf788c9bdd1bdd8/import_export/admin.py#L294).  It would be nice if this was wrapped in a form error.  So I'll look into this as well.

**Comment by matthewhegarty** [comment]
> To improve this PR, what about checking for dataset.headers just before trying to access dataset.dict? 

I had a look into importing files with no header row.  If done via the Admin site, it will not crash, but reports that 0 rows where imported.

If done via `import_data()`, then it just skips all rows, and nothing is imported.  The reason for this is that `get_or_init_instance()` just returns an empty object.  When the `skip_row()` comparison runs, it finds that all the `instance` fields match the `original` (because `original` is a clone of `instance`).

I also had a scan through some past issues, and couldn't see for sure that people have been hit by this.

So I don't think there is any great benefit to checking for `dataset.headers` before `dataset.dict` - feel free to contradict if you think I am wrong about this!

**Comment by matthewhegarty** [comment]
Closing - this is not going to be added.

**Pull request closed without merging**
