### PR TITLE
Add kazakh translations

### PR DESCRIPTION
**Pull request by MuslimBeibytuly**
**Problem**

Added kazakh translations

**Solution**

Generated them

**Acceptance Criteria**

link to: https://github.com/django-import-export/django-import-export/pull/1060

### CODE REVIEW

**Comment by MuslimBeibytuly** [comment]
@andrewgy8 what should I do to have it merged?:D I want to point this repository instead of fork in requirements of my projects:)

**Comment by andrewgy8** [comment]
@MuslimBeibytuly I will merge this once Travis gives the green light.

**Comment by MuslimBeibytuly** [comment]
@andrewgy8 perfect, thank you!:)

**Comment by MuslimBeibytuly** [comment]
@andrewgy8 ready:)

**Pull request merged**
