### PR TITLE
Add Kazakh translations.

### PR DESCRIPTION
**Pull request by MuslimBeibytuly**
**Problem**

What problem have you solved?

**Solution**

How did you solve the problem?

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

### CODE REVIEW

**Comment by MuslimBeibytuly** [comment]
@andrewgy8 can you help with it? I don't understand why pipelines fail

**Comment by aorzh** [comment]
@MuslimBeibytuly , did you saw traceback https://travis-ci.org/django-import-export/django-import-export/jobs/633190387#L276 ?
I did not looked inside issue but it's says: `ModuleNotFoundError: No module named 'settings'`

**Comment by andrewgy8** [comment]
Sorry @MuslimBeibytuly for the late reply. There seemed to be an issue with travis and the way ran our tests. If you rebase your branch from master, this PR should pass and we can go ahead and merge.

**Comment by claudep** [comment]
@MuslimBeibytuly Your po file has still the `#, fuzzy` marker in the header, and most header fields are still containing default values. Could you please complete those headers and rebase your PR?

**Comment by andrewgy8** [comment]
I would like this to get into master, however due to lack of activity Im going to close it. Please feel free to reopen it if we get everything up to date, etc.

**Pull request closed without merging**
