### PR TITLE
Fix #1006

### LINKED ISSUE #1006: Format field is always shown on Django 2.2
After upgrading to Django 2.2, the `Format` field is always shown in admins where I inherit from `ImportExportActionModelAdmin`, even thougt the export action is not selected. Here is a screenshot:
Skærmbillede fra 2019-10-02 16-05-52

### PR DESCRIPTION
**Pull request by beruic**
**Problem**

Fix #1006

**Solution**

Remove use of deprecated jQuery
Ensure correct order of JS media

**Acceptance Criteria**

This is hard to test formally, so someone please verify it.

### CODE REVIEW

**Comment by beruic** [comment]
I took a look at the failing tests, and it only fails against the current master because a class has been removed, so these changes has nothing to do with the failing tests. The same goes for #1008 and #1009 which currently has the same status.

**Comment by andrewgy8** [comment]
Hey @beruic ! Thanks for the contribution. To be honest, I'm no jquery wizard so I dont think Im the best to review this. If its ok with you, Id like to leave it open for a bit so we can perhaps get some other eyes on it. Is that ok?

**Comment by beruic** [comment]
I'm fine with that. Don't do anything you are not comfortable with :)

I'll just sum up the JS changes here below, to make it easier for any reviewer, and perhaps also for you and others likely experienced to understand the change:

https://api.jquery.com/ready/ states that:
> There is also $(document).on( "ready", handler ), deprecated as of jQuery 1.8 and removed in jQuery 3.0. Note that if the DOM becomes ready before this event is attached, the handler will not be executed.
, and Django 2.2 uses jQuery 3.3.1

https://bugs.jquery.com/ticket/11719 is just the ticket tracking this change.

In addition, my change of [line 13 in `action_formats.js`](https://github.com/django-import-export/django-import-export/pull/1007/files#diff-b497e83491e8021a7ea68c7f4f719f55L13)
`$actionsSelect.on('change', function() {` to `$actionsSelect.change(function() {` is mainly for readability and is based on the documentation at https://api.jquery.com/change/

I'm testing it in production soon, and so far see no issues in testing.

**Comment by beruic** [comment]
@bmihelac and @jdufresne , could any of you review or suggest a reviewer so we can merge this?

**Comment by manelclos** [comment]
Hi @beruic, we have the same problem in our applications when migrating to Django 2.2.

We reviewed your code and thought of a simpler solution, can you please check https://github.com/django-import-export/django-import-export/pull/1047 ?

This would not decrease coverage and it is the recommended way going forward. The `media` function is supposed to be used for more sophisticated requirements. Though the code looks good and I'm sure it fixes the problem too.

The commit about jQuery deprecations should be on a different PR IMHO.

@andrewgy8, @bmihelac, can you please take a look as well? Django 2.2 has been out for a while, it would be great to agree on a fix sooner than later :)

Thanks

**Comment by manelclos** [comment]
@beruic just checked and you are right about the jQuery deprecations, that is supposed to be affecting users since Django 2.1 https://docs.djangoproject.com/en/2.2/releases/2.1/#minor-features

So #1047 is only fixing our problems with jQuery, not the original problem in #1006

**Comment by beruic** [comment]
@andrewgy8 is that review not for you if @manelclos approves it?

**Comment by andrewgy8** [comment]
So to sum up @beruic , this fixes what is in #1047 plus more (ie what is mentioned in #1006)? Either is good for me. Just want to be clear before merging.

**Comment by beruic** [comment]
@andrewgy8 yes this fixes #1006 and there is no need to merge #1047 :)

**Pull request merged**
