### PR TITLE
Don't lump ValidationErrors together

### PR DESCRIPTION
**Pull request by vanschelven**
Don't lump ValidationErrors together as non-field-specific when they are field-specific

**Problem**
See #1465

**Solution**

Code to make a pretty box with errors that are tied to particular fields already existed. I simply tied into the existing code, and extended it from dealing only with `ValueError` to also deal with `ValidationError`

**Acceptance Criteria**

~This is a completely shoot-from-the-hip style PR; no new tests were created, I did not run tests, etc. I did briefly check, for my personal use-case, that a `ValidationError` raised in some widget does post-commit indeed show up as tied to a particular field.~

~I understand that this is in some way only half the work but my thinking is that something is better than nothing, and that others are better positioned to do the other half of the work. If nothing else, it make the raised issue more easily understandable.~

### CODE REVIEW

**Comment by pokken-magic** [comment]
I'll run the pipeline but generally not in favor of accepting PRs without tests that decrease test coverage. Definitely appreciate you sharing your code and idea! Seems like an interesting one. Will see what the pants looks like :) might be one worth squeaking through.  

That said I haven't looked into the use case for validation errors.  

In general probably a good idea to run the test suite locally if you can. Iirc it's pretty easy w tox

**Comment by vanschelven** [comment]
@pokken-magic / @matthewhegarty anything I can do to move this PR (or its sibbling) forward?

**Comment by matthewhegarty** [comment]
I won't be able to look at these PRs anytime soon, too much on at present.  Maybe things will ease off in the next few weeks.  Obviously we cannot guarantee they will be included - it depends on the nature of change and if there is any impact to existing implementations.  I haven't looked at them at all yet so I can't make any comment on that.

**Comment by matthewhegarty** [comment]
This seems reasonable to me but it would have to go in the next major release (v4) because it will change how errors are presented to the user, so could potentially break existing implementations.

**Comment by matthewhegarty** [comment]
I have reviewed and am closing.  Please see the comment in the [issue](https://github.com/django-import-export/django-import-export/issues/1465#issuecomment-1777550044).

**Pull request closed without merging**
