### PR TITLE
Add object info to RowResult

### PR DESCRIPTION
**Pull request by samhe**
Add object info to RowResult of IMPORT_TYPE_DELETE for log entry. Otherwise, it will prompt object_id not found error in IMPORT_DELETE case if I am not using the pk as the id_fields.

### CODE REVIEW

**Comment by bmihelac** [comment]
Thanks for contribution @samhe. Would you be kind to add a line to changelog and yourself to AUTHORS

**Comment by samhe** [comment]
@bmihelac I've update the changelog and AUTHORS, Is it suitable to merge this fix into upcoming release ? I need this fix in my project, thanks.

**Comment by manelclos** [comment]
LGTM. PR needs to be updated with current master.

**Comment by manelclos** [comment]
@samhe ping

**Pull request closed without merging**
