### PR TITLE
Update resources.py

### PR DESCRIPTION
**Pull request by devilsbibble**
get self-define [before_import] filtered dataset

### CODE REVIEW

**Comment by shaggyfrog** [comment]
I don't understand the change.

1) before_import doesn't return anything right now, so you are proposing to change the API with no reasoning and no tests.

2) You can already modify the dataset object inside before_import, so what's the point of returning it?

**Comment by devilsbibble** [comment]
The point is that i don't want to import all the sheet rows , rows which satisfy some conditions can be imported to database.

**Comment by shaggyfrog** [comment]
So delete the rows from `dataset` in `before_import()`.

**Comment by devilsbibble** [comment]
Yes,but rows can't be deleted in `before_import()`

**Comment by shaggyfrog** [comment]
Yes, rows can be deleted inside `before_import`. For example, if you override the function in your resource like this:

```
def before_import(self, dataset, using_transactions, dry_run, **kwargs):
    del dataset[20:]
```

Will delete everything after the first 20 rows.

**Comment by devilsbibble** [comment]
I know this method, but this method has some limit, like 
`for row in dataset:
      if row satisify some conditions:
            delete dataset[i]`,
the order of  `dataset ` will change, it has some errors

**Comment by shaggyfrog** [comment]
You can use `Resource.for_delete(row, instance)` and return `True` if you don't want to import the row, in which case the row will be skipped.

**Comment by devilsbibble** [comment]
oh, let me have a try~

**Comment by devilsbibble** [comment]
Yeah, `for_delete(row, instance)` solved my problem,thank you very much!

**Pull request closed without merging**
