### PR TITLE
Make deprecation warnings error on Travis

### PR DESCRIPTION
**Pull request by adamchainz**
**Problem**

As #1197.

**Solution**

Missed in #1197, which changed only the tox configuration and not for Travis.

**Acceptance Criteria**

Tests running on travis.

### CODE REVIEW

**Review by andrewgy8 — APPROVED** [review]
It works!

**Comment by adamchainz** [comment]
The error on travis is:

```
PendingDeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
```

I think this is because Travis uses an old Python 3.5.x release - 3.5.6, whilst the latest is 3.5.9. I have 3.5.9 locally and it seems the `import imp` line from `distutils` has been removed there (and on the latest 3.4.x release...).

Travis aren't so up to date these days - it's probably worth porting the tests over to GitHub Actions, which is very up to date. I'm happy to help with this since I did it for all my maintained projects - does that sound good to you @andrewgy8 ?

**Comment by andrewgy8** [comment]
Yeah I have been thinking about doing that on not only this project but on others. However, I have not had the time to do it. If you feel like going for it, please feel free. And let me know what I can do to help.

**Comment by matthewhegarty** [comment]
Included in #1306

**Pull request closed without merging**
