### PR TITLE
Export permission 299

### PR DESCRIPTION
**Pull request by mick88**
Resolves issue #608

### CODE REVIEW

**Comment by ZuluPro** [comment]
I don't think you should implement permissions like this.
Django has a great permissions system.

**Comment by mick88** [comment]
Hi @ZuluPro could you be more specific? The solution makes use of Django permission system.

**Comment by ZuluPro** [comment]
Oops, my bad, too early reading...

**Comment by manelclos** [comment]
I like the idea. Can you please add some tests? Coverage decreased (-0.1%) to 91.175%

**Comment by bmihelac** [comment]
Do we currently check permissions when importing data?
Also would this change be compatible with upcoming Django 2.1. new *view* permission and should we introduce new permission or *view* permission would be enough.

**Pull request closed without merging**
