### PR TITLE
Added new translations to Spanish and Spanish (Argentina)

### PR DESCRIPTION
**Pull request by smunoz-ml**
**Problem**

Added more texts to Spanish and Spanish (Argentina) translation files.

**Solution**

N/A

**Acceptance Criteria**

N/A

### CODE REVIEW

**Comment by matthewhegarty** [comment]
Thank you for submitting.  Feel free to add your name to `AUTHORS`

**Comment by smunoz-ml** [comment]
Thank you! Do I need to create another pull request to do that o I can just edit this one? I'm new to pull requests 😅

**Comment by matthewhegarty** [comment]
No need for new pull request - you can edit your copy of AUTHORS, commit and then push, that will create a new commit in the PR.  Or you can just edit AUTHORS directly via the Github console.  Then when you save it will commit it for you and it will appear in the PR.

**Comment by smunoz-ml** [comment]
Thank you!

**Pull request merged**
