### PR TITLE
Revert 'dark mode' css: causes issues in django2.2 (#1330)

### PR DESCRIPTION
**Pull request by matthewhegarty**
**Problem**

#1330 (dark mode makes "confirm import" page unreadable)

The issue seems to be that if using Django 2.2 and browsing in dark mode, then the page doesn't render correctly. 

**Solution**

Revert the change from #1323.

**Acceptance Criteria**

I have tested manually in Django 2.2 to confirm that the issue is no longer present.

- Start the example app with django 2.2
- Force refresh of the "confirm import" page to reload import.css
- Import a file and toggle light / dark mode in firefox to prove the issue is resolved.

### CODE REVIEW

**Review by manelclos — APPROVED** [review]
LGTM

**Comment by matthewhegarty** [comment]
Thanks @manelclos - do you have any availability to build a 2.6.1 release after I merge this? (I will correct the version number first)

**Comment by manelclos** [comment]
yes, please go ahead

**Comment by manelclos** [comment]
@matthewhegarty published https://pypi.org/project/django-import-export/2.6.1/

**Pull request merged**
