### PR TITLE
Checking for "not value" replaces all the 0's in a numeric import with the default value

### PR DESCRIPTION
**Pull request by aidanlister**

### CODE REVIEW

**Comment by bmihelac** [comment]
thanks for contribution @aidanlister.

This fix could bring some backward compatibility for some users, so I would like to have tests for this and as well to be sure not to broke again in the future.

**Comment by domenkozar** [comment]
A better fix would be to use a special value of `object()` if no value is provided instead of "".

**Comment by bmihelac** [comment]
@domenkozar what is *special value of object()*?

**Comment by aidanlister** [comment]
Something like

Class NoValue(object):
Pass

**Comment by bmihelac** [comment]
this should be fixed in e16b7a7. Please reopen if needed

**Pull request closed without merging**
