### PR TITLE
Minor refactoring to support filtering exports 

### PR DESCRIPTION
**Pull request by matthewhegarty**
**Problem**

#1578 
It is not possible to modify the Admin UI to include a custom field for export.  This is possible for [import](https://django-import-export.readthedocs.io/en/latest/advanced_usage.html#customize-admin-import-forms) but not export.

The bug is due to the fact that the form is [removed from kwargs](https://github.com/django-import-export/django-import-export/blob/0ff664cf646f310a9a7f76b1b7b10af5d8bd5b32/import_export/mixins.py#L163) hence cannot be used in custom Resources to filter the queryset.

**Solution**

- changed the `pop()` call so that the form remains in kwargs
- Added a new `filter_export()` hook to make it a lot easier to dynamically filter querysets for export
- Updated the example app to demonstrate using 'E Book'

**Acceptance Criteria**

- Ran integration tests
- Manual testing
- Updated Documentation

**Other refactoring**

- Split the test fixtures into 'book', 'categories' and 'author'
- Split import / export tests in `test_admin_integration.py` for better readability

### CODE REVIEW

**Review by pokken-magic — APPROVED** [review]
This looks like a useful tool. The general trend toward increasing granularity of operations makes sense to me and is something we will probably keep doing elsewhere.

**Comment by youtux** [comment]
Hi, can you please make a release with this fix? I can't customize the export form without this.

**Comment by matthewhegarty** [comment]
yes, my plan is to release it this week

**Comment by matthewhegarty** [comment]
Latest release (3.3.0) now available https://pypi.org/project/django-import-export/

**Pull request merged**
