### PR TITLE
Update changelog.rst

### PR DESCRIPTION
**Pull request by beruic**
Please review if anything is missing to make a new release

### CODE REVIEW

**Comment by manelclos** [comment]
@bmihelac can you review? After adding django 2.0 support and maybe some other PR it would be good to have a new release.

**Comment by bmihelac** [comment]
I'll to throught list ASAP

**Comment by mgrdcm** [comment]
All, I just did an accounting and verified that this PR does include all the PRs merged up through and including #585 on Mar 17, 2017.  Which means all these commits are not yet reflected:

https://github.com/django-import-export/django-import-export/compare/cc61562a54b5e86ea8eface48e8c7c814e616ede...0.5.1

I'm starting on that process now.

**Comment by mgrdcm** [comment]
OK, I have the rest in #679.

**Pull request merged**
