### PR TITLE
Related Descriptor Crash

### LINKED ISSUE #493: raise Error when model  has attribute __unicode__ which print some foreignKey value.
If A model has attribute `__unicode__`, foreignKey and print the foreignKey in `__unicode__`, when I import some new data, it will raise an Exception says `RelatedObjectDoesNotExist: XX has no yy.`
For example

```python
## models.py
title = models.CharField(verbose_name=u'需求内容')
proposer = models.ForeignKey(User, verbose_name=u'需求提出人', related_name='proposer')
    def __unicode__(self):
        return u'%s %s' % (self.proposer.username, self.title )
```

After reading the code in django-import-export, I found something wrong as follow:

```python
## resource.py
instance, new = self.get_or_init_instance(instance_loader, row)  # if row is new, will return an None instance
row_result.object_repr = force_text(instance) # try to get the foreignKey value, and raise Exception
```

### PR DESCRIPTION
**Pull request by jschneier**
I only write the properties when the row has been fully materialized, so the FKs are already there after saving.

Also, if we skip we don't write the `LogEntry`, so no need to write the properties.

Closes #493, #439, #459

### CODE REVIEW

**Comment by jschneier** [comment]
@bmihelac @shaggyfrog any comments? Seems like you are 2 of the maintainers. This fixes a very common and annoying issue that a lot of people are having with a minimum amount of code changes.

**Comment by bmihelac** [comment]
Thanks for contributing @jschneier 

This looks good to me. @shaggyfrog if you do not have any objections let's merge this in.

**Comment by shaggyfrog** [comment]
No objections :)

**Comment by bmihelac** [comment]
Merged, thanks!

**Comment by thauk-copperleaf** [comment]
I have just discovered a knockon bug from this change, when `row_result.import_type` gets set to something other than `RowResult.IMPORT_TYPE_ERROR` (like `RowResult.IMPORT_TYPE_NEW`), and an exception is thrown before it gets to set `row_result.object_id = instance.pk`.

In that case, `ImportMixin.generate_log_entries()` will attempt to access `row.object_id`, which doesn't exist.

**Comment by jschneier** [comment]
Not sure if that is caused by this patch.

I think [https://github.com/django-import-export/django-import-export/blob/650d5f1c57de17ed51933a40016d738a2e0bc6a9/import_export/resources.py#L431](this code) is a bit naive. Setting the result type to `IMPORT_TYPE_ERROR` in the exception handler is the most robust way I think.

**Comment by thauk-copperleaf** [comment]
I am fairly confident since if I locally undo the changes here to `admin.py`, then I no longer get an exception thrown by `ImportMixin.generate_log_entries()`. I believe all it would take to reproduce would be adding a test that has `Resource.import_obj()` throw an exception.

I tried moving `row_result.import_type = RowResult.IMPORT_TYPE_ERROR` into the exception handler, but that didn't work.

I'll continue investigating, but I think we don't want `row_result.import_type` to be anything but `RowResult.IMPORT_TYPE_ERROR` when an exception is thrown.

**Comment by thauk-copperleaf** [comment]
Actually, it does turn out that moving the statement into the exception handler does fix it for me. (I had a different problem in my test that I fixed.)

Writing a test for this is going to be tough. This won't happen with standard usage of the library; it requires that `ImportMixin.process_dataset()` be overridden and that `Resource.import_data()` be called with `raise_errors=False` with a dataset that triggers an exception to be thrown inside `Resource.import_row()`, after `row_result.import_type` is set, such that the resulting row error does not get raised by `Resource.import_data_inner()`, and the row result gets logged. Phewf.

**Comment by thauk-copperleaf** [comment]
Created PR with fix #543

**Pull request merged**
