### PR TITLE
1.8 compatibility

### PR DESCRIPTION
**Pull request by synotna**
Use ForeignObjectRel instead of RelatedObject
https://code.djangoproject.com/ticket/21414

### CODE REVIEW

**Comment by bmihelac** [comment]
@synotna thanks for your contribution. Is it possible to add fallback for older Django versions

ref #200

**Comment by synotna** [comment]
Ugh, seems it's not as trivial as hoped. 

```python
AttributeError: 'RelatedObject' object has no attribute 'get_internal_type'
```
Sorry for the pull request not going to the original ticket directly!

**Comment by synotna** [comment]
I ran out of time for today, hopefully this helps someone

```python
======================================================================
ERROR: test_related_one_to_one (core.tests.resources_tests.ModelResourceTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/synotna/django-import-export/tests/core/tests/resources_tests.py", line 348, in test_related_one_to_one
    class EntryResource(resources.ModelResource):
  File "tests/../import_export/resources.py", line 479, in __new__
    readonly=True)
  File "tests/../import_export/resources.py", line 534, in field_from_django_field
    FieldWidget = self.widget_from_django_field(django_field)
  File "tests/../import_export/resources.py", line 499, in widget_from_django_field
    internal_type = f.get_internal_type()
AttributeError: 'RelatedObject' object has no attribute 'get_internal_type'

----------------------------------------------------------------------
```

**Comment by fpruitt** [comment]
"""
======================================================================
ERROR: test_m2m_import_with_transactions (core.tests.resources_tests.ModelResourceTransactionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.3.5/lib/python3.3/site-packages/django/test/testcases.py", line 1010, in skip_wrapper
    return test_func(*args, **kwargs)
  File "/home/travis/build/bmihelac/django-import-export/tests/core/tests/resources_tests.py", line 458, in test_m2m_import_with_transactions
    use_transactions=True)
  File "tests/../import_export/resources.py", line 306, in import_data
    transaction.enter_transaction_management()
AttributeError: 'module' object has no attribute 'enter_transaction_management'
"""

This one fails because enter_transcation_management is a deprecated private API:
https://docs.djangoproject.com/en/1.7/_modules/django/db/transaction/

**Comment by bmihelac** [comment]
> AttributeError: 'RelatedObject' object has no attribute 'get_internal_type'

I noticed that for the case above this would work: 

    internal_type = f.field.get_internal_type()

But this is just hack. I would hopefully get some time to check this over the weekend.

**Comment by bmihelac** [comment]
https://github.com/bmihelac/django-import-export/pull/233 fixes other Django 1.8 compatibility issues while staying compatible with supported Django > 1.4. Please check if everything works for you.

**Pull request closed without merging**
