### PR TITLE
Creates `RelatedModelImportable` class

### PR DESCRIPTION
**Pull request by craiglabenz**
Changes:
- Allows importing a list of related models scoped to a single instance of another model. For example, uploading a set of books that all relate to a specific Author without adding an `author` column to the import file
- Updates to `django-suit`'s templates are also ready for submission

**Note**: This is my first foray into `rst`, so I'm hoping I didn't butcher my update to the documentation.

### CODE REVIEW

**Comment by psicom** [comment]
@bmihelac is there a chance getting this on the next release?

**Comment by craiglabenz** [comment]
@psicom Unfortunately, I don't expect @bmihelac has any intention of merging this commit. Or reviewing it, at this point. I'd recommend re-forking it (to update against `master`), and pip installing directly from a commit hash on your fork.

**Comment by psicom** [comment]
@craiglabenz Thanks, i'll try this solution.

**Comment by manelclos** [comment]
Adding needs patch as this is not current with master

**Pull request closed without merging**
