### PR TITLE
to_encoding unicode error

### PR DESCRIPTION
**Pull request by pkozlov**
After some test I have UnicodeDecodeError
This is solution that works for me

### CODE REVIEW

**Comment by pkozlov** [comment]
And csv is binary format? If yes, we must have solution to encode csv

**Comment by bmihelac** [comment]
I have reverted previous merge so it does not fail for users. We'll merge it back when it is ready. Please note that we support both Python 2.7.x and Python 3.3+

**Comment by pkozlov** [comment]
Previous merge is ok, because only binary data is unicode strings and in python 3 all strings is unicode. But this pr fails in python 3. I'm thinking about solution now.

**Comment by pkozlov** [comment]
In my case, I only need csv in cp1251 jn python 2.7 =)

**Comment by manelclos** [comment]
PR needs to be updated for current master and tests need to be added.

**Comment by manelclos** [comment]
Inactive. Closing. Please reopen if necessary.

**Pull request closed without merging**
