### PR TITLE
Add support for postgres ArrayField

### PR DESCRIPTION
**Pull request by thauk-copperleaf**
Add postgres `ArrayField` to `widget_from_django_field()` lookup and have it return a new widget, `SimpleArrayWidget`, when running Django >= 1.8.

### CODE REVIEW

**Comment by thauk-copperleaf** [comment]
Resolves #469

**Comment by bmihelac** [comment]
Thanks @thauk-copperleaf. Would it be possible to add some test with new functionality? It would make it much easier for other developers that are not familiar with `ArrayField` (like I am )

**Comment by thauk-copperleaf** [comment]
Here's a test. It took me a while how to elegantly create a migration that would only create the model for postgres.

**Comment by bmihelac** [comment]
Merged, thanks a lot!

**Pull request merged**
