### PR TITLE
Remove migrations

### LINKED ISSUE #1125: Demo not working out-of-the-box
It looks like that there is an issue with the migrations for the demo. With the latest checkout I get:

```bash
$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 12, in <module>
    execute_from_command_line(sys.argv)
[....]
export/tests/core/migrations/0004_bookwithchapters.py", line 17, in <module>
    class Migration(migrations.Migration):
  File "/home/demo/Documents/repos/django-import-export/tests/core/migrations/0004_bookwithchapters.py", line 32, in Migration
    ('data', data_field)
NameError: name 'data_field' is not defined
```

### PR DESCRIPTION
**Pull request by fabaff**
**Problem**
The setup of the Demo app was not possible in a clean `venv`.  

Fixes #1125

**Solution**

Removing the migrations.

```bash
 tests]$ python3 manage.py test
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......................................................................s................................................................................................ss
----------------------------------------------------------------------
Ran 169 tests in 5.936s

OK (skipped=3)
Destroying test database for alias 'default'...
```

**Acceptance Criteria**

See next PR #1127.

### CODE REVIEW

**Comment by fabaff** [comment]
Looks like that travis needs to be adjusted. Local `tox` is passing.

```bash
$ tox -e py38-djangomaster-tablibdev
GLOB sdist-make: /home/demo/Documents/repos/django-import-export/setup.py
py38-djangomaster-tablibdev create: /home/fab/Documents/repos/django-import-export/.tox/py38-djangomaster-tablibdev
py38-djangomaster-tablibdev installdeps: -egit+https://github.com/jazzband/tablib.git#egg=tablib, https://github.com/django/django/archive/master.tar.gz, -rrequirements/test.txt
py38-djangomaster-tablibdev inst: /home/fab/Documents/repos/django-import-export/.tox/.tmp/package/1/django-import-export-2.1.1.dev0.zip
py38-djangomaster-tablibdev installed: asgiref==3.2.7,defusedxml==0.6.0,diff-match-patch==20181111,Django==3.1,django-import-export==2.1.1.dev0,et-xmlfile==1.0.1,isort==4.3.21,jdcal==1.4.1,MarkupPy==1.14,mysqlclient==1.4.6,odfpy==1.4.1,openpyxl==3.0.3,psycopg2==2.8.5,pytz==2020.1,PyYAML==5.3.1,sqlparse==0.3.1,-e git+https://github.com/jazzband/tablib.git@16b556535445ed2a2347104f0e0604f59f066099#egg=tablib,xlrd==1.2.0,xlwt==1.3.0
py38-djangomaster-tablibdev run-test-pre: PYTHONHASHSEED='3275573066'
py38-djangomaster-tablibdev run-test: commands[0] | python /home/demo/Documents/repos/django-import-export/tests/manage.py test core
Creating test database for alias 'default'...
System check identified no issues (0 silenced).
......................................................................s................................................................................................ss
----------------------------------------------------------------------
Ran 169 tests in 7.407s

OK (skipped=3)
Destroying test database for alias 'default'...
____________________________________________________________________________ summary _____________________________________________________________________________
  py38-djangomaster-tablibdev: commands succeeded
  congratulations :)
```

**Comment by matthewhegarty** [comment]
It will be because the travis script sets the `IMPORT_EXPORT_TEST_TYPE` env var, which enables it to run against a Postgres / MySQL db.  Local tox only uses sqlite.

I don't know why sqlite is ok with the migrations not being run

**Comment by andrewgy8** [comment]
I agree with @matthewhegarty . Closing since this should not be done.

**Comment by fabaff** [comment]
Sorry, now I get it. The tests and demo app are combined.

> The install issues in #1125 should work if the dependencies are installed.

Hmm, what dependencies are you talking about? Is there more that's needed for the demo than mentioned in the `setup.py` file?

**Comment by matthewhegarty** [comment]
Yes, the migrations in the test app require that `psycopg2` is installed for (`JSONField`).  So installing the dependencies in `requirements/test.txt` in a venv should sort out the issue in #1125.

As a side note, this dependency won't be necessary in [Django 3.1](https://docs.djangoproject.com/en/dev/releases/3.1/#jsonfield-for-all-supported-database-backends)

**Pull request closed without merging**
