### PR TITLE
Fix deprecated Django 3.0 function usage

### PR DESCRIPTION
**Pull request by MuslimBeibytuly**
**Problem**

What problem have you solved?

**Solution**

How did you solve the problem?

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

### CODE REVIEW

**Comment by andrewgy8** [comment]
What happened to the Django 3 in Travis? I saw it in a commit but I didn’t see it in a diff. Did you remove it from this or?

**Comment by MuslimBeibytuly** [comment]
> What happened to the Django 3 in Travis? I saw it in a commit but I didn’t see it in a diff. Did you remove it from this or?
Added to pipeline, was fixing

**Comment by MuslimBeibytuly** [comment]
@andrewgy8 should I add more tests on anything? Coverage decreased, not good

**Comment by manelclos** [comment]
@MuslimBeibytuly can you please squash your commits?

**Comment by andrewgy8** [comment]
Thanks @MuslimBeibytuly ! It should be fine @manelclos since I squash all the commits anyways 😉

**Pull request merged**
