### PR TITLE
Fix: Importing in admin within a transaction gives TransactionManagem…

### PR DESCRIPTION
**Pull request by camilotorresf**
Fix: Importing in admin within a transaction gives TransactionManagementError.

If we are using MySQL as database, the django.contrib.admin app, and
some other configurations that run the admin views inside an atomic
block (a transaction), when importing data we now test if we are inside
an atomic block to know if the DB supports transactions, in addition to
previous check to see if the DB features supports transactions.

This is to solve issue #609.

### CODE REVIEW

**Comment by jrobichaud** [comment]
We have the same issue and this code fixes it.

**Comment by melbic** [comment]
According to https://github.com/django-import-export/django-import-export/issues/1100 that issue still exists. We are using our own Fork with this PR. Could you please reopen that PR and merge it? THanks

**Comment by claudep** [comment]
@bmihelac, @andrewgy8 Couldn't you remove that stale bot? It's a pain.

**Comment by okapies** [comment]
I think so too. import-export is a great library but has several issues to solve. I saw the stale bot closes several important issues/PRs before addressed.

**Pull request closed without merging**
