### PR TITLE
Refactor transaction handling

### PR DESCRIPTION
**Pull request by bmihelac**

### CODE REVIEW

**Comment by mgrdcm** [comment]
@bmihelac Could you fast-forward this (it's still showing diffs in the CHANGELOG file for instance) please?  Also, I see that this is assigned to "django-import-export/maintainers" for code review, but it appears you're the only person in that group? ;)

**Comment by bmihelac** [comment]
@mgrdcm rebased it to master branch.sorry for  misleading review request

**Comment by mgrdcm** [comment]
No worries!  I'll try to take a look tonight, though anyone else who can should go ahead!

**Comment by mgrdcm** [comment]
Not sure when I'm going to be able to do a thorough review of this, might be a few days.  @manelclos or @shaggyfrog can you take a look?

**Comment by manelclos** [comment]
LGTM, tests are passing (including Django 2.0 and master), plus coverage increases 0.6% Whoo-hoo!

**Comment by bmihelac** [comment]
merged, thanks for review

**Pull request merged**
