### PR TITLE
Support for multi database

### LINKED ISSUE #1137: Double insert of rows while importing
When importing a CSV via the admin interface, the rows in the sheet are being imported twice. Once when loading preview and once when confirming import. Importing with the `id` column left empty. I've used the library before and I've never faced this issue before. Super confused!

Django==2.1.3
django-import-export==2.1.0

```
class ReviewsResource(resources.ModelResource):
    class Meta:
        model = Review
        fields = ('id',  the remaining fields in the model...)
```

```
class Review(models.Model):
    .. few field definitions

    class Meta:
        managed = False
        db_table = 'review'

    def __str__(self):
        return str(self.id)
```

### PR DESCRIPTION
**Pull request by shivanshs9**
**Problem**

Fixes #1137 

**Solution**

Based on #583
Uses Django's DB router as a fallback to decide which DB connection to use.

**Acceptance Criteria**

Will add tests soon.

### CODE REVIEW

**Comment by shivanshs9** [comment]
Since I had a need for this use-case in my project, I am also maintaining a [branch](https://github.com/shivanshs9/django-import-export/tree/ft-multi-db) with this code:
```
django-import-export = { git = "https://github.com/shivanshs9/django-import-export.git", branch = "ft-multi-db" }
```

Once this PR is merged, it will no longer be needed.

**Comment by andrewgy8** [comment]
Hi @shivanshs9 . Since you remark that you will add tests soon, Im going to mark this as a draft. You can still get reviews and everything, and we will convert it to a PR when it meets our contributing guidelines. Cheers, Andrew

**Comment by vijay-anand-dev** [comment]
> Since I had a need for this use-case in my project, I am also maintaining a [branch](https://github.com/shivanshs9/django-import-export/tree/ft-multi-db) with this code:
> 
> ```
> django-import-export = { git = "https://github.com/shivanshs9/django-import-export.git", branch = "ft-multi-db" }
> ```
> 
> Once this PR is merged, it will no longer be needed.

How can I install this as a package?

**Comment by manelclos** [comment]
There is a similar PR [here](https://github.com/django-import-export/django-import-export/pull/1254), with tests

**Pull request closed without merging**
