### PR TITLE
Fix m2m import

### PR DESCRIPTION
**Pull request by AntoineD**
Importing a ManyToManyField did not work: a conditional test was bypassing the import, this test is not performed for other fields so I just removed it.
It may have side effects, I don't know.

### CODE REVIEW

**Comment by bmihelac** [comment]
Thanks for contributing @AntoineD.

Please not that `dry_run` attribute allows previewing of import changes and records are not really saved  when `dry_run=True` (unless transactions are used in which case m2m fields are saved and later rollback is performed)

**Comment by bmihelac** [comment]
If you think that there is an bug related to handling m2m imports, please open issue

**Comment by AntoineD** [comment]
I've opened an issue.

**Comment by bmihelac** [comment]
@AntoineD did you saw my comment regarding dry_run?

**Comment by AntoineD** [comment]
Yes I did.
Actually when using the plugin I did not go further than the preview step because it displayed no m2m data and I thought it was not working at all. So there seems to be at least a bug with the preview.
I have to give a try to go beyond the preview step, not sooner than next monday though.

**Pull request closed without merging**
