### PR TITLE
add possibility to override tmp storage class

### PR DESCRIPTION
**Pull request by AyumuKasuga**
I hope it will solve problem #251

By default file will be store in tmp directory as before, but now you can override tmp_storage_class option in ImportMixin with your own implementation.

Also I made two simple classes for store file in django cache and django file storage.

### CODE REVIEW

**Comment by bmihelac** [comment]
Thanks, this looks good to me. I would just wait for merging to see if there are any comments from other people for related #133

**Comment by sat2707** [comment]
Wow! I subscribe to waiting

**Comment by rhunwicks** [comment]
I won't be able to pull this commit and do hands on testing until next week at the earliest, but the overall approach looks good to me and I don't have any reservations about it. I think it is a much better approach than moving the data with the confirm form as JSON, and I can see how people could get around the horizontal scaling problem by choosing a shared storage - e.g. a shared cache such as memcache or redis, or the database. I use https://github.com/rhunwicks/django-database-files/ as a Django file storage backend that saves files to the database, and which would work. My fork uses BinaryField instead of Base64 encoded text.

**Comment by rhunwicks** [comment]
I tested this branch, and apart from having to resolve the merge conflict with ae6dd489b4556992fe224a912d3990baebe88fb0 by correcting the filenames used in this commit, it worked fine.

**Comment by rhunwicks** [comment]
@AyumuKasuga - please could you rebase your branch against the current master and issue a new PR, or add another commit to this PR to correct the file names passed to import_data to match what is currently in master.

**Comment by AyumuKasuga** [comment]
@rhunwicks done

**Comment by rhunwicks** [comment]
Thanks, but it still isn't quite correct. You are passing the `tmp_storage.name` through to the `import_data` whereas the fix in ae6dd489b4556992fe224a912d3990baebe88fb0 was to pass through the original file name instead of the temporary storage name:

```
            result = resource.import_data(dataset, dry_run=False,
                                          raise_errors=True,
                                          file_name=confirm_form.cleaned_data['original_file_name'],
                                          user=request.user)
```

**Comment by AyumuKasuga** [comment]
@rhunwicks sorry, I fixed this.

**Comment by bmihelac** [comment]
Merged, @AyumuKasuga thanks for patch, @rhunwicks thanks for review!

**Pull request merged**
