### PR TITLE
Delete  "{% load url from future %}" tags for work with django-1.9. Remove django-1.4 mentions.

### PR DESCRIPTION
**Pull request by mikhailmain**

### CODE REVIEW

**Comment by bmihelac** [comment]
@mikhailmain thanks for contributing. Can you remove django 1.4 from tox and travis and mention that django 1.4 is not supported in changelog

**Comment by mikhailmain** [comment]
I have no expirience with tox and travis. I hope my changes right.

**Comment by fabian** [comment]
Django 1.9 has been released today: https://www.djangoproject.com/weblog/2015/dec/01/django-19-released/

This PR is needed to make django-import-export work in Django 1.9.

**Comment by bmihelac** [comment]
Thanks, this is in 0.4.0

**Comment by fabian** [comment]
Perfect, can confirm django-import-export 0.4.0 works with Django 1.9.

Thank you!

**Comment by bmihelac** [comment]
good to know (besides ci test) and thanks for checking @fabian

**Pull request merged**
