### PR TITLE
Fix diff for objects with RelatedManager attributes

### PR DESCRIPTION
**Pull request by thauk-copperleaf**
Diffs are incorrect for objects with `RelatedManager` attributes since the lookup (using `export_field()`) obtains the same values for both `original` and `current`. To fix this, the fields in `original` need to be exported before `import_obj()` is called.

### CODE REVIEW

**Comment by thauk-copperleaf** [comment]
This PR will have a small conflict with #466 but I can easily fix up one if/when the other is merged.

**Comment by bmihelac** [comment]
Would it be possible to add some tests that shows previous/incorrect behaviour.

**Comment by thauk-copperleaf** [comment]
We discussed this for a while today and figured out the underlying problem. The existing diff behaviour assumes that a new model instance does not have an ID. This seems to be true with, say, sqlite. However, this is not true with postgres. When the "original" instance has the same ID as the "current" instance, the diff will fail to show a change (ins/del) with the related attribute.

I've added a test that will reproduce the bug with the existing Models/Resources in resources_tests.py with sqlite.

If you agree with our analysis, I will need to do one more commit to fix up the existing tests that use `get_diff()`.

**Comment by thauk-copperleaf** [comment]
I've gone ahead and fixed up the failing tests in ModelResourceTest.

**Comment by bmihelac** [comment]
@thauk-copperleaf thanks for your work. I will look into it and merge it as soon as possible.

**Comment by thauk-copperleaf** [comment]
I was thinking that creating a "Diff" object might be preferable to the repeated code to extract the fields.

Something like:
```
diff = Diff(original)
...
diff.with(instance)
...
row_result.diff = diff.as_html()
```

This would also eliminate the `deepcopy(instance)` call.

**Comment by bmihelac** [comment]
Merged, thanks! I have converted yaml fixture to json to avoid test dependency

**Comment by bmihelac** [comment]
> I was thinking that creating a "Diff" object might be preferable to the repeated code to extract the fields.

This looks like a good idea

**Comment by thauk-copperleaf** [comment]
Diff class proposed in #477

**Pull request merged**
