### PR TITLE
Refactor large test modules

### PR DESCRIPTION
**Pull request by PrashansaChaudhary**
**Problem**

What problem have you solved?

Refactor large test modules #1636

**Solution**

How did you solve the problem?
I have broken down the large test_admin_integration.py into 5 different and induvidual files which are unit testable on its own

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

### CODE REVIEW

**Comment by matthewhegarty** [comment]
Hi @PrashansaChaudhary 
Thanks for submitting.  I have changed the base branch to be `release-4` so that this can go in the v4 release (`release-3-x` now out of date).
However this means there is a conflict - is it possible you could resolve?

Feel free to add your name to AUTHORS as well.

**Comment by matthewhegarty** [comment]
You could also consider putting the new files in a new package, maybe called `admin_integration` e.g

```
- tests/
  - admin_integration/
    - test_actions.py
    - test_export.py
    - (etc)    
```

**Comment by matthewhegarty** [comment]
thanks - much appreciated.
`test_resources.py` is another big test module that would benefit from refactoring, if you were interested in taking a look.

**Comment by PrashansaChaudhary** [comment]
Thank you, sure, I will look into it.

Thanks and Regards,
Prashansa

**Comment by PrashansaChaudhary** [comment]
Hii Matthew,
I am new to open source contribution, as per my understanding, I need to refactor the code into branch version 4 which is a base branch and make a pull request from that. As that will create a new pull request, is that okay with you? Any clarity would help.

**Comment by matthewhegarty** [comment]
Hi Prashansa

No problem, thanks for helping us out, we appreciate it.  There should be no need to create a new PR, it should work like this (make sure you are on your `main` branch)

```
git fetch 
git merge origin/release-4
```

You will probably see a message saying that there is a conflict:

```
CONFLICT (content): Merge conflict in tests/core/tests/test_admin_integration.py
```

You can go ahead and resolve the conflict by editing the file (using PyCharm helps a lot here).  When you have resolved the conflict, you can commit all the changes.  Run the tests (`make test`) and then push to your remote branch with `git push origin main`.

If you have PyCharm, you can use 'compare with branch' to see your changes before you push them.  Let me know if you get stuck and I can help out.

**Comment by matthewhegarty** [comment]
Ideally you would want to work in a feature branch (not `main`) but we can sort that out after

**Pull request closed without merging**
