### PR TITLE
handle crash on start-up when `change_list_template` is a property

### PR DESCRIPTION
**Pull request by matthewhegarty**
**Problem**

Fix for issue #1521.  The server crashes when attempting to assign `change_list_template` if this has been decorated as a property in another library.  This is a workaround for issues which can arise when integrating import-export along with other libraries.

**Solution**

The `AttributeError` is caught and an exception is logged.  This doesn't crash the process and will give the user the opportunity to investigate and resolve.  I investigated testing if the attribute is implemented as a property, but this did not work.  It never evaluated the attribute as a property, only as a list.

**Acceptance Criteria**

- test included

### CODE REVIEW

**Review by pokken-magic — APPROVED** [review]
Nice!

**Comment by matthewhegarty** [comment]
Thanks for testing.  All very good points.  I'll take a look.

**Comment by matthewhegarty** [comment]
hi @ShaheedHaque I had another look, and have come up with the following

- The reason it doesn't work as it did in 2.x is because of the changes made in #1483, this was implemented so that import-export plays nicely with other plugins which define change list templates (ironically it has broken in this case).
- The issue we have is that `change_list_template` is a defined as a property in the polymorphic library, hence we cannot change that value and if we try to do so we get the error, so all we can do is catch that and continue.
- I have modified the log level from `exception` to `error` - I think this is valid - it is an unexpected error outside of our control, so we should log it.  If you don't want this in your logs you can configure the logging level for import-export in your application (i.e. set it to 'warning' level).
- To restore the 2.x changelist template, you can declare in your mixin:

```python
class CompanyPostalDetailAdmin(ImportExportMixin, poly_parentadmin.PolymorphicParentModelAdmin):
    change_list_template = 'admin/import_export/change_list_export.html'
```

I think this is a fair compromise between handling errors generated from integration alongside other libraries, and allowing flexibility for customisation.  

Please could you try the latest changes and let me know what you think.

**Comment by ShaheedHaque** [comment]
Thanks again for you prompt assistance.

I tried your suggestion to override the attribute by subclassing your mixin like this (I tried both versions as per the commented out line):

```
class ImportExportMixin(i_e_admin.ImportExportMixin):
    # change_list_template = 'admin/import_export/change_list_export.html'
    change_list_template = 'admin/import_export/change_list_import_export.html'
```

but Django crapped out saying TemplateDoesNotExist and producing this postmortem:

```
Template-loader postmortem
Django tried loading these templates, in this order:

Using engine django:

django.template.loaders.filesystem.Loader: /main/srhaque/bootstrap/source/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/django/contrib/admin/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/django/contrib/auth/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/django/contrib/postgres/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/bootstrapform_jinja/templates/admin/import_export/change_list_import_export.html (Source does not exist)
vvv recursion error here vvv
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/import_export/templates/admin/import_export/change_list_import_export.html (Skipped to avoid recursion)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/polymorphic/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/formtools/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/rest_framework/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/oauth2_provider/templates/admin/import_export/change_list_import_export.html (Source does not exist)
django.template.loaders.app_directories.Loader: /usr/local/lib/python3.10/dist-packages/drf_spectacular/templates/admin/import_export/change_list_import_export.html (Source does not exist)
```

Surprised? I was! I feel I am missing something obvious...but I just cannot see it.

**Comment by matthewhegarty** [comment]
Sounds similar to #1514.  I have been able to reproduce this now. `admin/import_export/change_list.html` extends `base_change_list_template`, so if this is somehow assigned to  `admin/import_export/change_list.html` (or any template which extends it) you'll see the issue.

To resolve, try this:

```python
class CompanyPostalDetailAdmin(ImportExportMixin, poly_parentadmin.PolymorphicParentModelAdmin):
    import_export_change_list_template = "admin/import_export/change_list_export.html"
```

**Comment by matthewhegarty** [comment]
> that gave me the original exception because the @property-decorated attribute was still in play

but presumably would be ok now because we are catching the exception and logging.  I guess you want to avoid the log statement altogether.

> So, I guess it is your call whether to bother with this patch or not

I think it will be useful to add it in - it will be much better for anyone in future not to have the app crash on start up.

I've added the method `init_change_list_template()` so there is always the option for users to override this and handle the change_list assignment anyway they want.

> Either way, many many thanks for patiently walk me to this point.

No problem - it's been useful for me to understand this issue in more detail, so thanks for providing the updates.

**Pull request merged**
