### PR TITLE
Add link to django-import-export-celery in docs

### PR DESCRIPTION
**Pull request by timthelion**
**Problem**

What problem have you solved?

Long running imports time out.

**Solution**

How did you solve the problem?

Moved long running imports to celery

**Acceptance Criteria**

Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?

### CODE REVIEW

**Comment by andrewgy8** [comment]
Congrats on the package @timthelion ! How is the project going? Is it being used in production anywhere?

**Comment by timthelion** [comment]
@andrewgy8 we have it on our test server now. It will go into production in a month or two. Currently I've only implemented import, because export is fast enough in our case.

**Comment by andrewgy8** [comment]
@timthelion Any update on this?

**Comment by timthelion** [comment]
The code works. It is deployed it in production but haven't trained anyone to use it yet 😃

We also have yet to implement exoprt, so far only.import is supported.

9. října 2019 8:57:42 SELČ, Andrew Graham-Yooll <notifications@github.com> napsal:

**Pull request merged**
