### PR TITLE
Fix import data no UTF-8 encoding

### PR DESCRIPTION
**Pull request by vhsantos**
**Problem**

You can't import a CSV (probably others formats too) that aren't in UTF-8 encoding.
If you try, you get this error:

`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 75: invalid start byte`

**Solution**

This PR add the **from_encoding** the open function as parameter.

### CODE REVIEW

**Comment by adamchainz** [comment]
I think we'd like to see a test here - the `from_encoding` parameter is already used in some places, so it would be good to test to show where exactly the problem exists.

**Comment by vhsantos** [comment]
Hello there,

no, the **from_encoding** in all project is used only in two functions **import_action** and **process_import** and it is called "after" the read, so, when the system read the file in a different encoding raise the error.  :-(

example code lines [141](https://github.com/django-import-export/django-import-export/blob/6adeee3fed7b901c116629c99a6eae9649b4b498/import_export/admin.py#L141) and [290](https://github.com/django-import-export/django-import-export/blob/6adeee3fed7b901c116629c99a6eae9649b4b498/import_export/admin.py#L290)

```
            data = tmp_storage.read(input_format.get_read_mode())
            if not input_format.is_binary() and self.**from_encoding**:
                data = force_str(data, self.**from_encoding**)
            dataset = input_format.create_dataset(data)
```

now, reading this code again, maybe the **if** there isn't necessary at all there.

Salu2

**Comment by adamchainz** [comment]
Okay that sounds very reasonable. I still think a test would be a good idea though. I'm not very familar with the project myself.

**Review by shs8313 — APPROVED** [review]

**Comment by andrewgy8** [comment]
Thanks for the contrib. Im going to convert this to a draft since it is lacking test coverage and documentation.

**Comment by matthewhegarty** [comment]
Superseded by #1306 and #1316

**Pull request closed without merging**
