### PR TITLE
Add mysql to travis

### PR DESCRIPTION
**Pull request by bmihelac**
---
name: Pull Request
about: Create a PR to contribute
title: ''
labels: ''
assignees: ''

---

**Problem**
What problem have you solved?

**Solution**
How did you solve the problem?

**Screenshots**
If applicable, add screenshots to help explain your solution.

**Acceptance Criteria**
Please make sure you meet the following.

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] New and existing unit tests pass on Travis with my changes

### CODE REVIEW

**Comment by andrewgy8** [comment]
Hmm. The failure that you are seeing now in travis is the same one I can reproduce locally.  I'm not sure how or why it happens.  I also seems like it s related to the encoding of the string in mysql.

**Comment by bmihelac** [comment]
@andrewgy8 this is because ordering is not set. should be fixed now.

**Comment by andrewgy8** [comment]
Great! I presume this is some internal mysql magic.

**Comment by bmihelac** [comment]
according to https://dba.stackexchange.com/a/6053

>  MySQL sorts the records however it wants without any guarantee of consistency.

**Comment by bmihelac** [comment]
thanks @andrewgy8

**Pull request merged**
