### PR TITLE
Fix missing migration on example app

### PR DESCRIPTION
**Pull request by josx**
**Problem**

Trying to run example app and following [documentation](https://django-import-export.readthedocs.io/en/latest/installation.html#example-app) i realized that when running `./manage.py makemigrations` creates a new migration file that is not present on repo.

**Solution**

Run locally `./manage.py makemigrations` and add to repo new migration file created `tests/core/migrations/0009_auto_20211111_0807.py`

### CODE REVIEW

**Comment by matthewhegarty** [comment]
Thanks - please can you update changelog.rst as well.  Feel free to add your name to AUTHORS as well.

**Comment by josx** [comment]
I have done what you asked for.
BTW I realized that changelog is not complete, serveral commits are missing.

**Comment by matthewhegarty** [comment]
> several commits are missing.

thanks - it will get sorted out before the release.

**Comment by matthewhegarty** [comment]
Please could you squash the commits into one, and then I can merge.

**Pull request merged**
