### PR TITLE
Add JSON B type field

### PR DESCRIPTION
**Pull request by andrewgy8**
**Problem**
What problem have you solved?

#285 

**Solution**
How did you solve the problem?

Add jsonb field to the resource field mapping.  Also added some more tests for array field data import.

**Screenshots**
If applicable, add screenshots to help explain your solution.

NA

**Acceptance Criteria**
Please make sure you meet the following.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] New and existing unit tests pass on Travis with my changes

### CODE REVIEW

**Comment by bmihelac** [comment]
Nice. One thing - is this a breaking change? I guess that previously PostgreSQL json fields were considered text fields, right? If yes, we should add a note in the documentation so users know that behaviour has changed.

**Comment by bmihelac** [comment]
Also, can we squash multiple commits in pull requests so we have more clear history?

**Comment by andrewgy8** [comment]
Sorry about the squash vs merge. I figured the PR incorporation method was not set forced on a user for a reason 🤦‍♂️ 

As far as the backwards compatibility goes, good catch! Yeah I believe you are right and I didn't think about it that way. I still have to update the change log and I presume docs will also need to be updated. Ill be sure to mention it there.

**Comment by bmihelac** [comment]
> Sorry about the squash vs merge. I figured the PR incorporation method was not set forced on a user for a reason

no problem :) we were not most consistent regarding this in the past

> As far as the backwards compatibility goes, good catch! Yeah I believe you are right and I didn't think about it that way. I still have to update the change log and I presume docs will also need to be updated. Ill be sure to mention it there.

Next release would be major, so this is a great time to introduce breaking changes. It will help users to know which breaking changes were introduced.

**Comment by sillycube** [comment]
I saw that this issue will be released with v2.0. Can I know when is it going to release?

**Pull request merged**
