### PR TITLE
Testing against Django 2.0 should not fail

### PR DESCRIPTION
**Pull request by manelclos**

### CODE REVIEW

**Comment by mgrdcm** [comment]
Ooh, do we support `2.0` now?

**Comment by manelclos** [comment]
Tests are not failing (the m2m thing is fixed too), so I'd say yes... I'll start moving some projects to 2.0 soon.

**Comment by manelclos** [comment]
all good, please review and merge

**Comment by bmihelac** [comment]
merged, thanks

**Pull request merged**
