### PR TITLE
Exapnd valid values for BooleanWidget

### PR DESCRIPTION
**Pull request by MinchinWeb**
Deals better with NULL/None values, which are now (Django 2.2) permitted in the regular fields.BooleanField (fields.NullBooleanField has been deprecated). Importing a field with TRUE/FALSE/NULL was otherwise failing (via turning all the NULL's into FALSE's).

**Problem**

The Boolean widget (which is used to diff an re-import) wasn't dealing with Null/None/Empty values, and instead casting them as "0" (i.e. `False`)

**Solution**

Explicitly add `""` (an empty string) and `None` as "None values".

**Acceptance Criteria**

*Have you written tests? Have you included screenshots of your changes if applicable?
Did you document your changes?*

No additional tests. No screenshot. I've added it to the Changelog (under v2.0.2).

### CODE REVIEW

**Comment by MinchinWeb** [comment]
@andrewgy8 : docs and tests added!

**Comment by MinchinWeb** [comment]
Is anything holding this up?

**Comment by andrewgy8** [comment]
@MinchinWeb There are some conflicts that need to be resolved.

**Comment by andrewgy8** [comment]
Thanks @MinchinWeb !

**Comment by andrewgy8** [comment]
Ill try to have this in the next minor release asap.

**Pull request merged**
