### PR TITLE
fix m2m widget clean

### PR DESCRIPTION
**Pull request by paveltyavin**

### CODE REVIEW

**Comment by mc8ain1** [comment]
@bmihelac any chance to merge this soon? I have the same issue (and others as mentioned in #177 as well) thx.

**Comment by bmihelac** [comment]
@thauk-copperleaf this looks good to me, any objections for merging?

**Comment by thauk-copperleaf** [comment]
LGTM

**Comment by bmihelac** [comment]
Merged, thanks!

**Pull request merged**
