### PR TITLE
Update zh_Hans translation

### PR DESCRIPTION
**Pull request by xslidian**
**Problem**

see #1159

**Solution**

Provide complete metadata. 

**Acceptance Criteria**

I saw a reference from another issue. It takes little time to make it 100% complete.

Changes are limited to this language file and should not destroy the whole project.

If I didn't catch future updates, you are welcome to ask anyone in the Debian/Ubuntu Chinese Simplified Language Team for help.

### CODE REVIEW

**Review by andrewgy8 — APPROVED** [review]
谢谢!

**Comment by andrewgy8** [comment]
Hi @xslidian ! Could you update this since #1279 has been merged?

**Comment by matthewhegarty** [comment]
@xslidian please can you resolve this so we can get this change into the next release.

**Comment by matthewhegarty** [comment]
Closing due to inactivity

**Pull request closed without merging**
