### PR TITLE
Mention Django 3.0 in classifiers

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
@andrewgy8 Do you think I could get the permission to triage (close) issues?

**Comment by andrewgy8** [comment]
@bmihelac has the power. I don’t see why not!

**Comment by claudep** [comment]
@bmihelac, any opinion to grant me (or not) permission to manage issues?

**Comment by bmihelac** [comment]
Hi @claudep , thanks for your contributionsthat you have already made. I have send you request to join the team.

**Comment by claudep** [comment]
Awesome, thanks!

**Pull request merged**
