### PR TITLE
More flexibility in ConfirmImportForm, forms and resource kwargs 

### PR DESCRIPTION
**Pull request by adibo**
I am a great fond of `django-import-export`, so thank you for all your efforts so far!

A couple of days ago, I came across a need to customize/modify the `ImportForm` as well as the`ConfirmImportForm`. Also I had a need to customize `kwargs` of a resource when importing. 
And although the `ImportForm` can be customized (via `get_import_form`) already, I could not found `get_confirm_import_form` equivalent. 
Hence my PR, with add-on flexibility on `kwargs` for the forms, resources and `import_data`.
It somehow addresses #758, #879, #880. 

Have a look! If this direction seems okey, I might add some info to docs too. 
Of course, any suggestions to improve are welcome!

### CODE REVIEW

**Comment by andrewgy8** [comment]
First off, thanks you for the contribution @adibo! 

A couple things before we can move ahead:
1. Any chance you could add some tests that describe and validate your changes? 
2. Could you rebase your branch? This would fix the failing pipeline and your conflicts.

Thanks again! And if you need any help, don't hesititate to ping me

**Comment by adibo** [comment]
Hi,
Thanks for your input. Apologies for not replying earlier. I was a way for 2 weeks.
ad 1) sure, I'll add some tests; have not done it yet since I was not sure if the PR will be okey with you
ad 2) yes
I hope to spend some time on this in the upcoming weekend.

**Comment by adibo** [comment]
Rebase done, test added, docs updated.
Cheers!

**Comment by adibo** [comment]
Thanks @bmihelac! :)
As for your question, I'm not sure what's your thinking. 
`get_import_form` and `get_confirm_import_form` both return class (type) of a respective form.
In the code used as:
```
...
form_type = self.get_import_form()
form_kwargs = self.get_form_kwargs(form_type, *args, **kwargs)
form = form_type(
    import_formats,
    request.POST or None,
    request.FILES or None,
    **form_kwargs)
...
```
Why would you want `request` to be included in `get_(confirm_)_import_form`?
Perhaps you meant `get_form_kwargs` or other methods? This, I guess, could be done.
Or did I missed something?

**Comment by bmihelac** [comment]
@adibo sorry, I misread that get_xx_form returns form class and not form. Everything looks good to me.

**Comment by adibo** [comment]
Hey, no problem! 
I think I know what you were after: unification of methods signatures?

If that's the case, I was also looking around and thinking a bit about it although in the context of the `Resource` class.
I came across the  need e.g. to have `dry_run` required in some methods, where it was not provided (in my case: e.g. in `after_import_row` as some irreversible actions would be taken only if it was not a dry run). 

Then I realized that although unification would be good, I may end up modifying/unifying all/most methods signatures without some deeper consideration/discussion.
And that that seemed somehow too much :)

At the end I ended up using mixins to store needed variables as class attributes. The approach solved my problem giving an access to the desired variable in any method I needed, without modifying the existing methods APIs. Like so:
```
class StoreDryRunMixin(object):
    """Mixin to store 'dry_run' as class a attribute `self._dry_run`"""

    def __init__(self, *args, **kwargs):
        self._dry_run = None
        super(StoreDryRunMixin, self).__init__(*args, **kwargs)

    def is_dry_run(self):
        return self._dry_run

    def import_data(self, dataset, dry_run=False, raise_errors=False,
                    use_transactions=None, collect_failed_rows=False,
                    **kwargs):
        self._dry_run = dry_run
        return super(StoreDryRunMixin, self).import_data(
            dataset,
            dry_run=dry_run,
            raise_errors=raise_errors,
            use_transactions=use_transactions,
            collect_failed_rows=collect_failed_rows,
            **kwargs)
```
But this would be a call for another PR, I guess :)

**Comment by adibo** [comment]
Any plans to conclude this PR?

**Comment by andrewgy8** [comment]
@adibo I dont see why not!

**Pull request merged**
