### PR TITLE
Fix #713: last day isn't included in results qs

### LINKED ISSUE #713: Last day isn't included in results queryset for export
Hi.
In case of export when one of filters is a datetime, behavior of export will not be compatible with data displayed inside admin. As I said in subject - last day is always missing in the queryset.

PR link: https://github.com/django-import-export/django-import-export/pull/714

### PR DESCRIPTION
**Pull request by piotr-szpetkowski**
issue https://github.com/django-import-export/django-import-export/issues/713

(this probably depends on https://github.com/django-import-export/django-import-export/pull/685)

### CODE REVIEW

**Comment by manelclos** [comment]
Please see that this PR breaks support for some older django versions that we *still* support

**Comment by piotr-szpetkowski** [comment]
@manelclos That is true and that's why I have mentioned that it should probably wait for #685 to land first.

**Comment by bmihelac** [comment]
thanks @piotr-szpetkowski, new PR is here https://github.com/django-import-export/django-import-export/pull/779 and waiting for CI results

**Comment by bmihelac** [comment]
merged in eddcacf21aaaba8e176e6161db3e0da6b33db400

**Comment by piotr-szpetkowski** [comment]
Thanks for taking care of that - I'm glad it was useful :tada:

**Pull request closed without merging**
