### PR TITLE
Drop support for Django <1.8 LTS

### PR DESCRIPTION
**Pull request by mgrdcm**
**This will be a breaking change for the purposes of semantic versioning, so we'll want to hold off until we're going to do a `1.0.0` release.**

Django 1.8 is the oldest version of Django currently supported by the Django Project, and will be supported until April 2018.

This PR also drops support for Python 2.6.

_Everyone:  Let me know if I missed anything.  I could move this to a `django-import-export` feature branch if we don't want to merge this right away._

### CODE REVIEW

**Comment by manelclos** [comment]
I agree with holding until 1.0.0

**Comment by bmihelac** [comment]
Can we create branch '0.6.x' from current master and merge this changes on master? Next release would then be 1.0.0.

**Comment by mgrdcm** [comment]
@bmihelac Good idea!  Though if `<1.0.0` is going into bugfix/maintenance mode, I'd think we'd want the `0.6.x` branch to based off of tag `0.6.0` rather than the current `master` branch, as `master` contains a bunch of unrelated changes we probably want to save for `1.0.0` now.

**Comment by bmihelac** [comment]
@mgrdcm or we can release `0.6.1` now and base 0.6.x on `0.6.1` tag

**Comment by mgrdcm** [comment]
@bmihelac Agreed!  There's not a ton since `0.6.0` though.  I have no opinion either way.

**Comment by bmihelac** [comment]
I think we are ready for 1.0. If there is no other suggestion:

* I will create branch 0.7.x (for any security or other important fix needed for older Django versions)
* merge this PR
* Release 1.0

@mgrdcm, @thauk-copperleaf, @manelclos did I forgot anything?

**Comment by manelclos** [comment]
Django 1.8 is supported "Until at least April 2018" (https://www.djangoproject.com/download/). LGTM otherwise.

**Comment by mgrdcm** [comment]
Hey @manelclos and @bmihelac!  Sorry I've been distracted with other things.  I just fixed the merge conflict on this.

**Comment by bmihelac** [comment]
No problem @mgrdcm and thanks!

I'll go with https://github.com/django-import-export/django-import-export/pull/685#issuecomment-358217890 asap.

**Comment by bmihelac** [comment]
Merged in e6d9be730babc2a54d535b8a95862e5f5606ca26, thanks!

**Comment by gabn88** [comment]
Just curious, will it also support Django 2.0 now?

**Pull request merged**
