### PR TITLE
feat: adaptive column width

### PR DESCRIPTION
**Pull request by Birdi7**
**Problem**

This PR changes column width to be adaptive and based on the values in column. The width will be the length of the longest entry in a column.

https://github.com/django-import-export/django-import-export/issues/500 is a somehow-related issue

**Solution**

The PR adopts a new feature for adaptive column width in tablib. It should be merged after https://github.com/jazzband/tablib/pull/516 will be merged and new version will be released.

**Acceptance Criteria**

I didn't write the tests as I didn't found any for XLSX exporting. Let me know if this is required

I didn't document the changes, as I didn't found the documentation on format classes. Let me know if this is required

### CODE REVIEW

**Comment by matthewhegarty** [comment]
Thanks for this.  I suggest that this would go into our forthcoming v3 release.  Please can you rebase onto `release-3-x` and push again?  We would also need tests before it can be merged.

**Comment by matthewhegarty** [comment]
I've changed the base branch from `main` to `release-3-x`

**Comment by Birdi7** [comment]
Thank you for the comment! I'll add tests after tablib merge

**Comment by matthewhegarty** [comment]
Closing due to inactivity

**Comment by harshhes** [comment]
I think this PR isn't merged yet in the latest release as I couldn't find the code that is added in this PR

**Comment by matthewhegarty** [comment]
Hi, Yes it was closed without being merged because it was incomplete.  Feel free to pick it up and submit a new PR.

**Pull request closed without merging**
