### PR TITLE
Fix primary key import issue, add test

### LINKED ISSUE #1852: Related model with primary key causes import exception (regression)
**Describe the bug**
If you have a model which uses an explicit primary key, imports fail

**To Reproduce**
1. Create model A with "primary_key=True"
2. Create model B which references (ForeignKey) model A
3. Export data from Model B
4. Import that file into Model B

This produces the failure: `Line number: 1 - 'id'`

**Versions (please complete the following information):**
 - Django Import Export: 4.0.3
 - Python 3.11.8
 - Django 5.0.6

**Expected behavior**
Models import normally. This was working in 3.x

**Screenshots**
image

**Additional context**

### PR DESCRIPTION
**Pull request by roharvey**
**Problem**

Closes #1852 

**Solution**

Replaced `id` reference with `pk`

**Acceptance Criteria**

I wrote a test, probably very poorly so please update or advise on changes. The test failed before the widget.py change and passed afterwards.
After the fix was in place, using the test app and following the steps in the ticket, I got past the error:
image

### CODE REVIEW

**Review by matthewhegarty — APPROVED** [review]
Thanks so much for raising this and crafting a fix, much appreciated :+1:

I have refactored to use classes from the example application, I hope that's ok with you.

Feel free to add your name to AUTHORS if you wish.

**Comment by roharvey** [comment]
> Thanks so much for raising this and crafting a fix, much appreciated 👍
> 
> I have refactored to use classes from the example application, I hope that's ok with you.
> 
> Feel free to add your name to AUTHORS if you wish.

Thanks! Yes much better test, I figured I was barking up the wrong tree. I added myself to AUTHORS and appreciate your responsiveness!

One little thing... it looks like a test for #1846 (test_declared_field_export_order()) made its way into this PR. Not that it bothers me, but I wondered if that was intentional?

**Comment by matthewhegarty** [comment]
I will merge soon once tests complete. Thanks for all your input on this PR.

> it looks like a test for https://github.com/django-import-export/django-import-export/issues/1846 (test_declared_field_export_order()) made its way into this PR.

I think that is because I merged the new test in a separate PR.  If you pull and merge from upstream it should fix it.  The test isn't showing in this PR's changes so it should be ok.

**Comment by PetrDlouhy** [comment]
@matthewhegarty I think there is typo in the code. The commit description states `[test for Resource export order with declared fields (1868)`, but the comment in the commit points to #1846.

**Pull request merged**
