### PR TITLE
show formats selector only when export action is selected

### PR DESCRIPTION
**Pull request by manelclos**
Hi,

This little javascript hides the formats select and shows it only when the export action is selected. It is quite simple but IMHO a good usability improvement.

Should you like the idea, we also need to modify the documentation to include the collectstatic step in the installation.

### CODE REVIEW

**Comment by bmihelac** [comment]
looks good. default collectstatic would handle this the same way it handles other admin static files, right?

**Comment by manelclos** [comment]
yes, let me add the step to the documentation.

**Comment by manelclos** [comment]
I should get an rst editor :-P. This is now ready to merge.

**Comment by bmihelac** [comment]
thanks!

**Pull request merged**
