### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by petrmifek**
Tweaked the "import finished ..." message to be translatable and cleaned it up a bit (mainly to use the already available verbose name of the model from the meta parameters).

The Czech translation coverage was updated to 100% of translatable strings.

### CODE REVIEW

**Comment by bmihelac** [comment]
Merged, thanks a lot!

**Comment by thauk-copperleaf** [comment]
This resulted in a broken build https://travis-ci.org/django-import-export/django-import-export/jobs/228040871

**Comment by thauk-copperleaf** [comment]
@petrmifek Can you fix?

**Comment by petrmifek** [comment]
Ah, sorry, missed that. I guess I can't amend this pull request anymore, can I? I created a new pull request with a fix - please see #604

**Pull request merged**
