### PR TITLE
Add diff class to generate diff HTML (and fix build)

### PR DESCRIPTION
**Pull request by thauk-copperleaf**
As per discussion in #470

### CODE REVIEW

**Comment by thauk-copperleaf** [comment]
I kept the `original` object (and the `deepcopy()` call that creates) because of the line

    if self.skip_row(instance, original):

Is this good enough for now, or should I also try to eliminate the `skip_row()` call?

**Comment by thauk-copperleaf** [comment]
I noticed the build was failing after your last merge for 3.x builds: https://travis-ci.org/django-import-export/django-import-export/builds/138169098

So I've fixed one of the dependency issues here since I was refactoring the function that caused it.

**Comment by thauk-copperleaf** [comment]
Yes, that seems to have fixed the build :) https://travis-ci.org/django-import-export/django-import-export/builds/138219309

**Comment by leotop** [comment]
Yes, this fix work for python3. Thank you very much.

**Comment by bmihelac** [comment]
Merged, thanks!

**Pull request merged**
