### PR TITLE
Generalized post-save behavior

### PR DESCRIPTION
**Pull request by mcdeoliveira**
**Problem**

Generalized handling of objects with related fields for which save has to be postponed after the instance has been saved/created. This is a generalization of the behavior currently supported only by the ManyToManyWidget.

**Solution**

More details on the issue are discussed in #1028.

**Acceptance Criteria**

Tests have been added and documentation of the code has been written. I have not changed the api documentation but will be happy to do it if the PR is accepted.

### CODE REVIEW

**Comment by flaper87** [comment]
I recently ran into a case where something like this is needed. I'd love to see this going in :D 

Thanks for the PR

**Comment by andrewgy8** [comment]
Is this something still desired? If so, is this a breaking change since we changing the api of the `import_field`?

**Comment by pokken-magic** [comment]
This is really cool behavior that could probably stand to get picked up. the is_m2m setting has some pretty irksome side effects in building a generic ResourceWidget (that can save created foreign key and m2m related items). 

I'm not sure this version of the code is the best way to do it but it addresses a real problem we should address.

**Comment by mcdeoliveira** [comment]
That would be great. I have not followed up with the latest versions of the code but this is a very useful behavior that I'm sure other users would benefit from.

**Comment by matthewhegarty** [comment]
Is there any appetite to pick this up to try to get it over the line? Mauricio? Ryan?  If we were to pick it up, it might be suitable for inclusion in v4.

**Comment by pokken-magic** [comment]
Argh, this is really useful code. I am utterly buried at the moment from a cognitive load perspective so I don't think so. I could make time for a detailed review and pulling the code down and trying it potentially if it were updated/rebased/etc.

**Comment by matthewhegarty** [comment]
I'm planning v4 now - maybe by the end of the year.  Perhaps with a bit of work this could go in, otherwise I will close due to lack of activity.

**Comment by matthewhegarty** [comment]
Hi All

Last call on this one.  If anyone wants to volunteer to include in either v4 or v5 let me know, otherwise I'll close.

**Pull request closed without merging**
