### PR TITLE
Use future value of ManyToManyField to check if value would change

### PR DESCRIPTION
**Pull request by manelclos**
**Problem**

Issue #1270 

How did you solve the problem?

**Acceptance Criteria**

No tests broke. Specific tests pending based on acceptance of the change.

### CODE REVIEW

**Comment by matthewhegarty** [comment]
Looks good. It would be ideal to add a unit test which confirms the bug, and perhaps refer to the issue id in the comment?

**Comment by manelclos** [comment]
@matthewhegarty you're right, I'll do some more work on it, moving to draft, thanks!

**Comment by manelclos** [comment]
@matthewhegarty I've added tests. I noticed that this PR also modifies the API, so would be a candidate to merge along https://github.com/django-import-export/django-import-export/pull/1278

**Comment by matthewhegarty** [comment]
> I noticed that this PR also modifies the API

Yes - it would probably affect a lot of users as well, because the `skip_row()` docstring recommends overriding the method.  

I tried to think if there is anyway of achieving this without breaking the API, but couldn't think of a clean way.

I'm planning to modify #1278 to avoid breaking the API.

**Comment by felixmeziere** [comment]
Any update on this issue? Still using the library from this branch 😬

**Comment by manelclos** [comment]
Hi @matthewhegarty! I need these changes and the branch is now gone. Is it safe to start using `release-3-x` branch?

**Comment by matthewhegarty** [comment]
Hi @manelclos - yes it is a stable branch so you can use it for testing.

**Pull request merged**
