### PR TITLE
[3.0] Improve import form compatibility

### PR DESCRIPTION
**Pull request by manelclos**
Fix for #1432

Avoid crashing and print a warning about what needs to be changed to get it fully working in 3.0

### CODE REVIEW

**Comment by manelclos** [comment]
Hi @matthewhegarty, something like this would make the upgrade to 3.0 a bit easier. Please let me know what you think.

**Review by matthewhegarty — CHANGES_REQUESTED** [review]
Looks good.  Thanks for testing and creating this PR.

I expect you will add a note in the changelog under breaking changes as well?

**Comment by manelclos** [comment]
@matthewhegarty working on this today, lets see how much I can get done.

**Comment by manelclos** [comment]
working on the test, feel free to correct the breaking changes note I just added.

**Comment by manelclos** [comment]
Hi @matthewhegarty tests just added. Let me know what you think. I'll squash commits before merge.

**Review by matthewhegarty — APPROVED** [review]
LGTM.  Presumably you were able to manually test the fix in your code base which subclassed Form (not ImportExportFormBase)

**Comment by manelclos** [comment]
Yes, after using the new base class everything works as expected.

**Pull request merged**
