### PR TITLE
ajuste widget datawidget, format date in methot render.   https://github.com/django-import-export/django-import-export/issues/1131

### PR DESCRIPTION
**Pull request by ixerv-jalvarez**
**Problem**

What problem have you solved?
https://github.com/django-import-export/django-import-export/issues/1131#issue-613532498

There is a model with two date fields, and a Resource invoking Datewidget for these fields.
In the import by ADMIN, for all formats. JSON, Excel YMAL. an error is obtained while validating the import. Specifically the DateWidget in its "Render" method, an error is obtained, because the variable "VALUE" is in STRING format, and when implementing the "strftime" method, the exception is generated.
`AttributeError: ' str 'objeto no tiene atributo' strftime '`

**Solution**

Located in the "render" method of the "DateWidget" class, in widget.py. it is observed that the "value" attribute is of type "STRING", therefore, the "strftime" method cannot be accessed.

Therefore, value is replaced by the clean (value) method, obtaining the correct type of data to apply "strftime".

clean(value): returns an appropriate Python object for an imported value.
**Acceptance Criteria**

Requirements.txt
```

asgiref==3.2.3
astroid==2.3.3
attrs==19.3.0
beautifulsoup4==4.8.2
cattrs==1.0.0
colorama==0.4.3
defusedxml==0.6.0
diff-match-patch==20181111
dj-database-url==0.5.0
Django==3.0.2
django-crispy-forms==1.8.1
-e git+https://github.com/jazzband/django-debug-toolbar.git@fb4ffee379f93c861d2a2cf836656e5388eb1d41#egg=django_debug_toolbar
django-import-export==2.1.0
django-model-utils==4.0.0
django-notifications-hq==1.6.0
django-serializable-model==0.0.6
django-session-timeout==0.1.0
django-summernote==0.8.11.6
django-widget-tweaks==1.4.8
djangorestframework==3.11.0
et-xmlfile==1.0.1
gunicorn==20.0.4
html-json-forms==1.1.1
html5lib==1.0.1
isort==4.3.21
jdcal==1.4.1
jsonfield==3.1.0
lazy-object-proxy==1.4.3
MarkupPy==1.14
mccabe==0.6.1
odfpy==1.4.1
openpyxl==3.0.3
pdfkit==0.6.1
Pillow==7.0.0
psycopg2-binary==2.8.4
pylint==2.4.4
pylint-django==2.0.13
pylint-plugin-utils==0.6
PyPDF2==1.26.0
pytz==2019.3
PyYAML==5.3.1
reportlab==3.5.42
six==1.14.0
soupsieve==1.9.5
sqlparse==0.3.0
swapper==1.1.2.post1
tablib==1.1.0
typed-ast==1.4.1
webencodings==0.5.1
whitenoise==5.0.1
wrapt==1.11.2
xhtml2pdf==0.2.4
xlrd==1.2.0
xlwt==1.3.0
```

Se tiene el modelo: 

```
class structure(models.Model):
    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    company = models.ForeignKey(to='organizational.Company', null=True, blank=True, on_delete=models.SET_NULL)
    division = models.ForeignKey("Division", null=True, blank=True, on_delete=models.SET_NULL)
    location = models.ForeignKey("Location", null=True, blank=True, on_delete=models.SET_NULL)
    businessUnit = models.ForeignKey("BusinessUnit", null=True, blank=True, on_delete=models.SET_NULL)
    departament = models.ForeignKey("Departament", null=True, blank=True, on_delete=models.SET_NULL)
    position = models.ForeignKey("Position", null=True, blank=True, on_delete=models.SET_NULL)
    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(default='9999-12-31', auto_now=False, auto_now_add=False)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
```

resources.py
```

class StructureResource(resources.ModelResource):
    employee = fields.Field(
                column_name='employee',
                attribute='employee',
                widget=ForeignKeyWidget(Employee, 'code')) 
    company = fields.Field(
                column_name='company',
                attribute='company',
                widget=ForeignKeyWidget(Company, 'code')) 
    division = fields.Field(
                column_name='division',
                attribute='division',
                widget=ForeignKeyWidget(Division, 'code'))
    location  = fields.Field(
                column_name='location',
                attribute='location',
                widget=ForeignKeyWidget(Location, 'code'))
    businessUnit  = fields.Field(
        
                column_name='businessUnit ',
                attribute='businessUnit',
                widget=ForeignKeyWidget(BusinessUnit, 'code'))
    departament  = fields.Field(
                column_name='departament',
                attribute='departament',
                widget=ForeignKeyWidget(Departament, 'code'))
    position  = fields.Field(
                column_name='position',
                attribute='position',
                widget=ForeignKeyWidget(Position, 'code'))

    start_date  = fields.Field(
                column_name='start_date',
                attribute='start_date',               
                widget=DateWidget( format =("%Y-%m-%d") ))
    end_date  = fields.Field(   
                column_name='end_date',
                attribute='end_date',               
                widget=DateWidget( format =("%Y-%m-%d") ))   
```
 in admin.py

```
from django.contrib import admin
from apps.organizational.models import Company,structure

from import_export.admin import ImportExportModelAdmin,ImportMixin ,ImportExportMixin
from .resources import  StructureResource

admin.site.register(structure)
admin.site.unregister(structure)

class StructureAdmin(ImportExportModelAdmin):
    resource_class = StructureResource  

admin.site.register(structure, StructureAdmin) 
```
Los datos a importar son en formato JSON

```
[
  {
    "employee": "100003",
    "company": "CO10",
    "division": "PP",
    "location": "CO/BOG/CorpCenter",
    "businessUnit ": "OPS",
    "departament": "70000057",
    "position": "700003",
    "start_date": "1900-01-01",
    "end_date": "9999-12-31"
  }
]
```

Import is performed in the admin with the data and the following message is obtained:

```
Número de línea: 1 - 'str' object has no attribute 'year'
100003, CO10, PP, CO/BOG/CorpCenter, OPS, 70000057, 700003, 1900-01-01, 9999-12-31
Traceback (most recent call last):
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\widgets.py", line 151, in render
return value.strftime(self.formats[0])
AttributeError: 'str' object has no attribute 'strftime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\resources.py", line 531, in import_row
diff = self.get_diff_class()(self, original, new)
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\resources.py", line 178, in __init__
self.left = self._export_resource_fields(resource, instance)
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\resources.py", line 199, in _export_resource_fields
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\resources.py", line 199, in <listcomp>
return [resource.export_field(f, instance) if instance else "" for f in resource.get_user_visible_fields()]
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\resources.py", line 708, in export_field
return field.export(obj)
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\fields.py", line 125, in export
return self.widget.render(value, obj)
File "C:\django\enviroments\developenv1\lib\site-packages\import_export\widgets.py", line 153, in render
return datetime_safe.new_date(value).strftime(self.formats[0])
File "C:\django\enviroments\developenv1\lib\site-packages\django\utils\datetime_safe.py", line 42, in new_date
return date(d.year, d.month, d.day)
AttributeError: 'str' object has no attribute 'year'
```

error_valid_import_structure

in widget.py render method of datewidget

code_render_widgetDate

adjustment is made! change value to self.clean (value)

ajust_render_clean

we do the data import again

prueba del ajuste

datos ok

Datos TestSuccessFull

it is recommended to make this adjustment

```
  def render(self, value, obj=None):
        if not value:
            return ""
        try:          
            return self.clean(value).strftime(self.formats[0])
        except:
            return datetime_safe.new_date(value).strftime(self.formats[0])
```

### CODE REVIEW

**Comment by ixerv-jalvarez** [comment]
> Hola @ ixerv-jalvarez ! ¿Puede agregar algunas pruebas a este PR por favor antes de revisarlo?

Hi Andre, attached to the initial comment, find the tests carried out, since 24 days it has been working correctly in my project.
Pudiste revisarlo mi comentario incial y las evidencias adjuntas?
quedo atento a tus comentarios.
Saludos

**Comment by andrewgy8** [comment]
Hola @ixerv-jalvarez ! We will need at least one test for this change. Im going to mark it as draft, until then. Thanks!

**Comment by matthewhegarty** [comment]
Hi @ixerv-jalvarez - I cannot reproduce this.  I have tried

- Loading test admin site
- Exporting books to xlsx, json, yaml
- Importing back into admin site

This all works fine.  

Please can you try to reproduce using the main branch, and let me know if it still fails?

**Comment by matthewhegarty** [comment]
Closing due to inactivity

**Pull request closed without merging**
